services:
  django-app:
    image: allawy/django-app
    env_file:
      - ./project/.env
    restart: unless-stopped
    volumes:
      - static_volume:/app/project/staticfiles

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/project/staticfiles:ro
    depends_on:
      - django-app

volumes:
  static_volume:
