services:
  django-app:
    build:
      context: .
      target: development
    container_name: django-app-dev
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: project.settings.dev
    volumes:
      - ./project:/app/project
      - ./project/requirements.txt:/app/requirements.txt
      - static_volume:/app/project/staticfiles



# docker compose --env-file ./project/.env -f docker-compose.yml -f docker-compose.dev.yml up --build -d
