name: Run Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # settings: [project.settings.dev, project.settings.prod]
         settings: [project.settings.dev]
    env:
      DJANGO_SETTINGS_MODULE: ${{ matrix.settings }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: Run tests
        run: |
          cd project
          python manage.py makemigrations
          python manage.py migrate
          pytest